# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_changeset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='changeset_type',
            field=models.CharField(choices=[('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], db_index=True, default='I', editable=False, max_length=1, verbose_name='Changeset Type'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
    ]
