# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_changeset', '0003_restore_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='object_id',
            field=models.BigIntegerField(db_index=True, editable=False, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='object_uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True, verbose_name='Object UUID'),
        ),
    ]
